-- 143_ingestion_auto.sql — FRAÎCHEUR / F6 : automatisation par source, sous interrupteur, en fenêtre nocturne.
--
-- CONTEXTE : F6 est le SEUL lot de la série F qui EXÉCUTE une ingestion. Pour chaque source en cas (a) (complet, outillé, sans
-- étape manuelle : DILA, PRADA, Sitadel, Cadastre), un interrupteur permet une réingestion AUTOMATIQUE, la NUIT (Postgres, dev,
-- MinIO tournent sur le même Mac à disque limité). Défauts SÛRS : tout DÉSACTIVÉ ; fenêtre 3h-6h. BD TOPO bâtiment n'a JAMAIS
-- d'interrupteur (bascule édition-spécifique + golden) ; les cas (b)/(c) non plus.
--
-- ① config_veille : 4 interrupteurs PAR SOURCE (défaut false) + fenêtre nocturne (début/fin, défaut 3/6, bornes 0..23).
-- ② TABLE ingestion_auto_journal : une ligne par TENTATIVE (source, nuit_du, début, fin, résultat succes/echec/refus, motif,
--    erreur). Sert à la fois de trace consultable ET de garde « une seule tentative par source et par nuit » (présence d'une
--    ligne (source, nuit_du)). L'insertion se fait AU DÉBUT (résultat 'echec' pessimiste) → un plantage laisse la tentative
--    tracée, pas de reprise en boucle la même nuit.
--
-- ADDITIVE / SÛRE : ADD COLUMN IF NOT EXISTS sur le singleton + CREATE TABLE IF NOT EXISTS. Aucune donnée touchée, aucun
-- DROP/DELETE/TRUNCATE, aucun trigger. N'affecte NI le moteur SVAV, NI config_scoring, NI le golden. Une transaction. Rejouable.
--
-- ⚠️ REPLI CÔTÉ CODE : tant que cette migration n'est PAS appliquée, les lecteurs isolés renvoient les défauts (tout désactivé)
-- et le journal est réputé absent (to_regclass) → AUCUNE ingestion ne peut partir. C'est l'état de la machine entre commit et
-- application. Prouvé par les tests (repli config all-off → aucun runner appelé).
--
-- APPLICATION MANUELLE (Arno), arrêt au 1er échec :
--   set -a && source .env && set +a
--   psql -v ON_ERROR_STOP=1 "$DATABASE_URL" -f db/migrations/143_ingestion_auto.sql
-- DRY-RUN : remplacer « COMMIT; » par « ROLLBACK; ». TU NE L'APPLIQUES PAS (migration livrée NON APPLIQUÉE).

BEGIN;

ALTER TABLE config_veille ADD COLUMN IF NOT EXISTS dila_auto_active     boolean NOT NULL DEFAULT false;
ALTER TABLE config_veille ADD COLUMN IF NOT EXISTS prada_auto_active    boolean NOT NULL DEFAULT false;
ALTER TABLE config_veille ADD COLUMN IF NOT EXISTS sitadel_auto_active  boolean NOT NULL DEFAULT false;
ALTER TABLE config_veille ADD COLUMN IF NOT EXISTS cadastre_auto_active boolean NOT NULL DEFAULT false;
ALTER TABLE config_veille ADD COLUMN IF NOT EXISTS ingestion_auto_fenetre_debut integer NOT NULL DEFAULT 3;
ALTER TABLE config_veille ADD COLUMN IF NOT EXISTS ingestion_auto_fenetre_fin   integer NOT NULL DEFAULT 6;

ALTER TABLE config_veille DROP CONSTRAINT IF EXISTS config_veille_ingestion_fenetre_chk;
ALTER TABLE config_veille ADD CONSTRAINT config_veille_ingestion_fenetre_chk
  CHECK (ingestion_auto_fenetre_debut BETWEEN 0 AND 23 AND ingestion_auto_fenetre_fin BETWEEN 0 AND 23);

COMMENT ON COLUMN config_veille.dila_auto_active IS 'FRAÎCHEUR F6 — réingestion nocturne AUTOMATIQUE de DILA. Défaut false (geste explicite d''Arno requis).';
COMMENT ON COLUMN config_veille.ingestion_auto_fenetre_debut IS 'FRAÎCHEUR F6 — heure de début de la fenêtre nocturne d''ingestion auto (0..23). Défaut 3.';
COMMENT ON COLUMN config_veille.ingestion_auto_fenetre_fin IS 'FRAÎCHEUR F6 — heure de fin de la fenêtre nocturne d''ingestion auto (0..23). Défaut 6.';

CREATE TABLE IF NOT EXISTS ingestion_auto_journal (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source     text NOT NULL,                                   -- clé de source (dila, prada, sitadel, cadastre)
  nuit_du    date NOT NULL,                                   -- nuit de rattachement (garde « 1 tentative / source / nuit »)
  demarre_le timestamptz NOT NULL DEFAULT now(),
  fini_le    timestamptz,
  resultat   text NOT NULL CHECK (resultat IN ('succes', 'echec', 'refus')),
  motif      text,                                            -- refus : 'disque_insuffisant' ; ou 'en cours' au démarrage
  erreur     text                                             -- message d'erreur complet en cas d'échec
);
CREATE INDEX IF NOT EXISTS ingestion_auto_journal_source_nuit_idx ON ingestion_auto_journal (source, nuit_du);

COMMENT ON TABLE ingestion_auto_journal IS
  'FRAÎCHEUR F6 — trace des tentatives d''ingestion AUTOMATIQUE (nocturne). Une ligne = une tentative ; présence d''une ligne (source, nuit_du) = « déjà tentée cette nuit » (pas de reprise en boucle). Insertion au DÉBUT (resultat pessimiste ''echec'') pour tracer même un plantage.';

COMMIT;

-- ═════════════════════════════════════════════════════════════════════════════
-- VÉRIFICATION (s'exécute au lancement) :
\echo '>>> ① interrupteurs + fenêtre (défauts) :'
SELECT column_name, data_type, column_default FROM information_schema.columns
WHERE table_name = 'config_veille'
  AND column_name IN ('dila_auto_active','prada_auto_active','sitadel_auto_active','cadastre_auto_active','ingestion_auto_fenetre_debut','ingestion_auto_fenetre_fin')
ORDER BY column_name;
\echo '>>> ② contrainte de fenêtre :'
SELECT conname FROM pg_constraint WHERE conname = 'config_veille_ingestion_fenetre_chk';
\echo '>>> ③ table de trace :'
SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'ingestion_auto_journal' ORDER BY ordinal_position;
