-- 144_alerte_mises_a_jour.sql — FRAÎCHEUR / G4 : alerte e-mail GROUPÉE ET RARE quand des bases sont prêtes à être mises à jour.
--
-- CONTEXTE : la pastille (G3) s'allume mais Arno doit ouvrir l'admin pour la voir. G4 l'avertit par e-mail — GROUPÉ (un seul
-- message listant toutes les sources) et RARE (un e-mail UNIQUEMENT quand la situation CHANGE : une nouvelle source apparaît
-- dans le jeu en attente). Tant que la liste est identique, aucun rappel. Liste vide → jamais d'e-mail.
--
-- ① config_veille.alerte_maj_active (boolean, DEFAULT false) — interrupteur DÉDIÉ (jamais alerte_active, qui est le récap R8).
--    Défaut false : rien ne part tant qu'Arno ne l'active pas dans l'interface. Destinataire = config_veille.alerte_email (R8).
-- ② config_veille.alerte_maj_empreinte (text, nullable) — empreinte de la DERNIÈRE liste traitée (cles triées, ex. « dila|prada »).
--    Sert d'anti-spam : on ne renvoie que si l'empreinte change ET qu'une nouvelle source apparaît. Marquée seulement sur SUCCÈS
--    d'envoi ; absorbée (sans e-mail) quand la liste ne fait que rétrécir.
-- ③ TABLE alerte_maj_journal — trace des envois (envoye_le, empreinte, destinataire, sujet, résultat envoyee/erreur, erreur).
--
-- ADDITIVE / SÛRE : ADD COLUMN IF NOT EXISTS sur le singleton + CREATE TABLE IF NOT EXISTS. Aucune donnée touchée, aucun
-- DROP/DELETE/TRUNCATE, aucun trigger. N'affecte NI le moteur SVAV, NI config_scoring, NI le golden, NI un gabarit d'e-mail
-- existant. Une transaction. Rejouable.
--
-- ⚠️ REPLI CÔTÉ CODE : migration absente → la lecture de alerte_maj_active jette → défaut false → AUCUN envoi possible entre le
-- commit et l'application. Prouvé par test.
--
-- APPLICATION MANUELLE (Arno), arrêt au 1er échec :
--   set -a && source .env && set +a
--   psql -v ON_ERROR_STOP=1 "$DATABASE_URL" -f db/migrations/144_alerte_mises_a_jour.sql
-- DRY-RUN : remplacer « COMMIT; » par « ROLLBACK; ». TU NE L'APPLIQUES PAS (migration livrée NON APPLIQUÉE).

BEGIN;

ALTER TABLE config_veille ADD COLUMN IF NOT EXISTS alerte_maj_active    boolean NOT NULL DEFAULT false;
ALTER TABLE config_veille ADD COLUMN IF NOT EXISTS alerte_maj_empreinte text;

COMMENT ON COLUMN config_veille.alerte_maj_active IS
  'FRAÎCHEUR G4 — interrupteur DÉDIÉ de l''alerte e-mail « bases prêtes à mettre à jour ». Défaut false (geste explicite d''Arno requis). Destinataire = alerte_email.';
COMMENT ON COLUMN config_veille.alerte_maj_empreinte IS
  'FRAÎCHEUR G4 — empreinte (cles triées, ex. « dila|prada ») de la dernière liste traitée. Anti-spam : e-mail seulement si l''empreinte change ET qu''une nouvelle source apparaît. Marquée sur succès d''envoi uniquement.';

CREATE TABLE IF NOT EXISTS alerte_maj_journal (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  envoye_le    timestamptz NOT NULL DEFAULT now(),
  empreinte    text NOT NULL,                                  -- empreinte de la liste au moment de l'envoi
  destinataire text NOT NULL,
  sujet        text NOT NULL,
  resultat     text NOT NULL CHECK (resultat IN ('envoyee', 'erreur')),
  erreur       text                                            -- message d'erreur complet en cas d'échec d'envoi
);

COMMENT ON TABLE alerte_maj_journal IS
  'FRAÎCHEUR G4 — trace des alertes e-mail « bases prêtes à mettre à jour ». Une ligne par tentative d''envoi (succès ou échec).';

COMMIT;

-- ═════════════════════════════════════════════════════════════════════════════
-- VÉRIFICATION (s'exécute au lancement) :
\echo '>>> ① interrupteur + empreinte (défauts) :'
SELECT column_name, data_type, column_default FROM information_schema.columns
WHERE table_name = 'config_veille' AND column_name IN ('alerte_maj_active', 'alerte_maj_empreinte') ORDER BY column_name;
\echo '>>> ② table de trace :'
SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'alerte_maj_journal' ORDER BY ordinal_position;
