-- 154_rattachement_suivi_auto.sql — RATT-AUTO : brique de veille « rejeu automatique du suivi de rattachement ».
--
-- CONTEXTE : un permis dont la projection est validée passe en `en_attente_bati` et rien ne l'en sort — le rejeu du suivi
-- (`permis:rattachement-suivre`) est un script MANUEL jamais planifié. On installe une brique de veille (executerVeille, étape
-- isolée après l'ingestion nocturne) qui rejoue `suivreRattachement` sur les SEULS dossiers `en_attente_bati`. Le jour où une
-- édition BD TOPO plus récente que le snapshot livre le bâti attendu, le dossier bascule seul en `arbitrage_demande` (décision
-- humaine). Tant qu'aucune édition neuve n'a été ingérée, la brique trouve 0 et ne fait rien — inoffensif.
--
-- CE LOT AJOUTE DEUX OBJETS, strictement ADDITIFS :
-- ① config_veille.rattachement_suivi_auto_active (boolean, DEFAULT false) — INTERRUPTEUR (pilotage sans code, écran Réglages →
--    thème « Rattachement au bâti »). Défaut false, comme TOUS les interrupteurs d'automatisation (relance_auto_active,
--    saisine_cada_auto_active, *_auto_active d'ingestion, alerte_maj_active) : appliquer la migration ne DÉCLENCHE rien ; Arno
--    l'active d'un clic quand il le veut. Pas de CHECK (un booléen n'a pas de plage).
-- ② TABLE rattachement_suivi_auto_journal — une ligne par PASSAGE : combien de dossiers examinés, combien ont basculé, et le
--    résultat. Un passage qui trouve 0 (aucun dossier / aucune bascule) est 'succes', JAMAIS 'echec' (CHECK sur la liste fermée).
--    Miroir d'ingestion_auto_journal.
--
-- 🔴 GARDE : ce lot ne touche NI `batiment`, NI le moteur de verdict SVAV, NI `permis_polygone_altitude`, NI le golden Asnières.
--    La brique n'INJECTE aucune altitude et n'utilise JAMAIS l'emprise reconstituée : la détection reste 100 % bâti BD TOPO réel
--    vs snapshot figé (mécanique de `suivreRattachement`, inchangée).
--
-- SÛR : DDL strictement ADDITIVE (ADD COLUMN / CREATE TABLE / INDEX « IF NOT EXISTS »). Aucun DROP, aucun ALTER destructif,
-- aucune écriture de données. GOLDEN-SAFE. Idempotente. Une seule transaction. AUCUN ENVOI. Requiert config_veille (048) et
-- permis_rattachement (116). Application MANUELLE (Arno), arrêt au 1er échec :
--   set -a && source .env && set +a
--   psql -v ON_ERROR_STOP=1 "$DATABASE_URL" -f db/migrations/154_rattachement_suivi_auto.sql
-- DRY-RUN : remplacer le « COMMIT; » final par « ROLLBACK; ». TU NE L'APPLIQUES PAS (migration livrée NON APPLIQUÉE).

BEGIN;

-- ① INTERRUPTEUR (pilotage sans code) — opt-in, défaut false.
ALTER TABLE config_veille ADD COLUMN IF NOT EXISTS rattachement_suivi_auto_active boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN config_veille.rattachement_suivi_auto_active IS
  'RATT-AUTO — rejouer automatiquement, à chaque tick de la veille, le suivi des permis « en attente de bâti » ? Opt-in (défaut false). ON : dès qu''une mise à jour BD TOPO fait apparaître le bâti attendu, le permis passe seul en « arbitrage_demande » (décision humaine ; AUCUNE altitude injectée). Sans effet visible tant qu''aucune édition plus récente n''est ingérée.';

-- ② JOURNAL des passages — un passage 0/0 est un SUCCÈS (jamais un échec).
CREATE TABLE IF NOT EXISTS rattachement_suivi_auto_journal (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passe_le     timestamptz NOT NULL DEFAULT now(),
  nb_examines  int NOT NULL DEFAULT 0,   -- dossiers `en_attente_bati` rejoués
  nb_bascules  int NOT NULL DEFAULT 0,   -- ceux ayant QUITTÉ `en_attente_bati` (vers arbitrage_demande / valide auto)
  resultat     text NOT NULL,
  erreur       text,
  CONSTRAINT rattachement_suivi_auto_journal_resultat_chk CHECK (resultat IN ('succes', 'echec'))
);
CREATE INDEX IF NOT EXISTS rattachement_suivi_auto_journal_passe_le_idx ON rattachement_suivi_auto_journal (passe_le DESC);

COMMENT ON TABLE rattachement_suivi_auto_journal IS
  'RATT-AUTO — une ligne par passage de la brique de rejeu automatique du suivi. nb_examines/nb_bascules = ce qui a été fait ; resultat = succes (y compris 0/0) | echec (exception seulement).';

COMMIT;

-- ═════════════════════════════════════════════════════════════════════════════
-- VÉRIFICATION POST-APPLICATION (à lancer À LA MAIN) :
--   SELECT column_name, data_type, column_default FROM information_schema.columns
--     WHERE table_name='config_veille' AND column_name='rattachement_suivi_auto_active'; -- boolean, false
--   SELECT to_regclass('public.rattachement_suivi_auto_journal'); -- non NULL
--   \d rattachement_suivi_auto_journal  -- resultat CHECK IN ('succes','echec'), index sur passe_le DESC
